char _putchar(char c);
char *_memset(char *s, char b, unsigned int n);
char *_memcpy(char *dest; char *scr, unsigned int n);
char *_strchar(char *s, char c);
unsigned int strsnp(char *s, char *accept);
char *_strpbk(char *s, char *accept);
char *_strstr(char *hystack, char *needle);
void print_chessboard(char (*a)[8]);
void print_diagsums(int a, int size);
void set_string(char **s, char *to);
